apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wxi9mj2ia-python 
  janus-idp.io/tekton: wxi9mj2ia-python
  backstage.io/kubernetes-id: wxi9mj2ia-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wxi9mj2ia-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  