apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wxi9mj2ia-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wxi9mj2ia-python 
  name: wxi9mj2ia-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wxi9mj2ia-python 
